language: objective-c
script: xctool -project TestIphone.xcodeproj -scheme TestIphone build  -sdk iphoneos
  CODE_SIGN_IDENTITY="iPhone Developer" PROVISIONING_PROFILE="50b33cac-87ca-4434-ba91-1d23a2f26840"
before_script:
- .travis/add_signing_key.sh
after_script:
- .travis/remove_signing_key.sh
env:
  global:
    secure: jWVQRqqXhFPywRsjk4Psva0/P/wFpoDp3cigOc1TX5GUl/MUrYfgJW/Y+u3U934d/jmebyJ6u4LoLgse+IA2oOkl8/M5BDY6FmnHt8fUDeD6HHSmaIPWnFIqALODqfI87ye6+f+ISO5tA8DjS9NOivKZnSwH5056xLvoKkkY8Tz4UqlC2vNRDy90YvMObRnahnOgKho26/EWEjTT6oLAuVQBQ+0Clrz8V9EIKH3ISC+LF2X078EALl3DkkKqxwhhOXO5W9ZDLbDaVM/C7LMmoEw/jYuDjwyCbaMQjJyIV2+psUH/O7q+5oEcdJA/OXZynoWtBhDuVojUbSZPvY9y1kGVSjy+sc6coy+9WymUTq5kcVL0M7TkbmtRgOb9Zka/0seeDT+6futJSJSq1qEeJGVIp0OoTHqWrEdwOMuALd+4GyatExaPaOoDPI/370+8fLeUV28j4CH8f7PMJ7RyuyD+0oZAYxFtCVCMtQBl6gtO4Hlnli43WbQNz0z9/hIB6N2mxa30fzwFkiFIttgBx5b8AC7YX25WqcAcI5nFLQHmAoqaSTic1C+R1BHSvClAevewwwJ88IctEf+KQHM9/XKujFclN1ukjfRuEQlgZYjdVIXU6mL6ol407Z7MtUj5o9mQryVwScDRdsIQZXGzNijHBrXAQEN96dhXhE+INgA=
before_install:
- openssl aes-256-cbc -K $encrypted_5e75db2e2fa3_key -iv $encrypted_5e75db2e2fa3_iv
  -in .travis/secrets.tar.enc -out .travis/secrets.tar -d
