language: objective-c
script: xctool -project TestIphone.xcodeproj -scheme TestIphone build  -sdk iphoneos
  CODE_SIGN_IDENTITY="iPhone Developer" PROVISIONING_PROFILE="9ac65f30-2f34-4acc-aecb-d8d9d8bce542"
before_script:
- .travis/add_signing_key.sh
after_script:
- .travis/remove_signing_key.sh
env:
  global:
    secure: XVaK8Nq6DuSWCTIrCJd/6qwxNctda5JHgYwOG2qc1wXHA95Lv076KFnJ1YyzQ6RKO6wzbvu58t2S4NXqPmDz/tlvy9NHMFf2O8Gqmg/3sBP1kSPR9tKM/1729MrznoVKLhFkY9VBWOsmvm6Bb/G81Ks10HLsenP7ZWEgT0T6vea7+lqiU3JIjt/Sl5CsImTnx6ju/X8xxq/4XgaLmUQ59SkcOBflmG8ZnjcqHJWvf86tvzOQe/Bg/ax84PPSOzMedObiQtvhIY9899lyEZZqjCVY3ExusWtEH17p6PXliQ2aatNOD2cpj10bd+9pNe5np2dSFq0GNs4P+SWLdhqboLE764sa9Rv+BogIfxLGb6C+PDnODbb2q6yc2EPmIjO/1DL4DRwUebGOtQr/rMEdjXVe9bD9xoOsa9KRDhheYECVud8o+Ygmq7eyB4d7swZIv2ozK+GLqDymq3q0oz8lE0V7V3X3axt4IgsbRWYEPLD5Ke25U2JuR5RPwsLQKb1S7nO9ZtOUL2a5g5pXMTU3HPtDKcOdrQnmzv01Gvx6UDWj+kFXD2ABfDJnnkIHOqpvb//56GQL7RkFLKgaxLkDAWd1rgHdrVZaGCf8OMYK5pphsyYyNFe8rhgxztaG4l3bmwAc+7p0xVQaY71Uctyh7unE5K88LHE7itup4wo6FRk=
before_install:
- openssl aes-256-cbc -K $encrypted_5e75db2e2fa3_key -iv $encrypted_5e75db2e2fa3_iv
  -in .travis/secrets.tar.enc -out .travis/secrets.tar -d
